import { MaterialCommunityIcons } from '@expo/vector-icons';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { useState } from 'react';
import { colors } from '../src/shared/theme/colors';
const themes=['간단한 한 끼','캠핑','가족 식사','저예산 요리','15분 요리','저칼로리','파티'];
const themeMeta: Record<string, { icon: keyof typeof MaterialCommunityIcons.glyphMap; badgeColor: string; iconColor: string; subtitle: string }> = {
  '간단한 한 끼': { icon: 'home-city-outline', badgeColor: '#EEEDFE', iconColor: colors.primary, subtitle: '간단하게 한끼' },
  '캠핑': { icon: 'campfire', badgeColor: '#FAEEDA', iconColor: '#854F0B', subtitle: '야외에서도 든든하게' },
  '가족 식사': { icon: 'account-group-outline', badgeColor: '#FBEAF0', iconColor: '#993556', subtitle: '함께 먹는 식탁' },
  '저예산 요리': { icon: 'cash-multiple', badgeColor: '#EEEDFE', iconColor: colors.primary, subtitle: '알뜰하고 맛있게' },
  '15분 요리': { icon: 'lightning-bolt-outline', badgeColor: '#FAEEDA', iconColor: '#854F0B', subtitle: '빠르게 완성' },
  '저칼로리': { icon: 'food-apple-outline', badgeColor: '#E1F5EE', iconColor: '#0F6E56', subtitle: '가볍고 든든하게' },
  '파티': { icon: 'party-popper', badgeColor: '#FBEAF0', iconColor: '#993556', subtitle: '즐거운 한상' },
};
export default function Themes(){const [query,setQuery]=useState('');const filtered=themes.filter(t=>t.includes(query.trim()));return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.container} showsVerticalScrollIndicator={false}><View style={s.headerRow}><Pressable style={s.iconButton} onPress={()=>router.back()}><MaterialCommunityIcons name="arrow-left" size={16} color={colors.muted} /></Pressable><Text style={s.headerTitle}>테마로 찾기</Text></View><Text style={s.eyebrow}>TODAYPICK · RECIPE ASSISTANT</Text><Text style={s.title}>오늘 상황에 맞는{'\n'}요리를 골라보세요</Text><Text style={s.subtitle}>테마를 선택하면 딱 맞는 레시피를 바로 추천해드려요.</Text><View style={s.searchBox}><MaterialCommunityIcons name="magnify" size={16} color={colors.muted} style={s.searchIcon}/><TextInput value={query} onChangeText={setQuery} placeholder="원하는 테마를 검색해보세요" placeholderTextColor={colors.muted} style={s.input}/></View><Text style={s.sectionTitle}>인기 테마</Text><View style={s.grid}>{filtered.map(t=>{const meta=themeMeta[t];return <Pressable key={t} style={s.card} onPress={()=>router.push({pathname:'/results',params:{theme:t}})}><View style={[s.badge,{backgroundColor:meta.badgeColor}]}><MaterialCommunityIcons name={meta.icon} size={18} color={meta.iconColor}/></View><Text style={s.cardText}>{t}</Text><Text style={s.cardSub}>{meta.subtitle}</Text></Pressable>})}</View><Text style={s.sectionTitle}>계절 테마</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}>{['#여름보양식','#냉면','#삼계탕','#입맛없을때'].map(tag=><Pressable key={tag} style={s.tag}><Text style={s.tagText}>{tag}</Text></Pressable>)}</ScrollView></ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},container:{padding:24,paddingBottom:32},headerRow:{flexDirection:'row',alignItems:'center',gap:10,marginBottom:20},iconButton:{width:32,height:32,borderRadius:16,alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:colors.line,backgroundColor:colors.surfaceTint},headerTitle:{fontSize:15,fontWeight:'600',color:colors.ink},eyebrow:{fontSize:11,letterSpacing:1.5,color:colors.primary,fontWeight:'800',marginBottom:6},title:{fontSize:22,fontWeight:'800',color:colors.ink,lineHeight:32,marginBottom:8},subtitle:{fontSize:14,lineHeight:22,color:colors.muted,marginBottom:20},searchBox:{borderWidth:1,borderColor:colors.line,borderRadius:16,backgroundColor:colors.surface,paddingLeft:38,paddingRight:14,paddingVertical:4,marginBottom:20},searchIcon:{position:'absolute',left:12,top:15},input:{fontSize:15,color:colors.ink,paddingVertical:10},sectionTitle:{fontSize:14,fontWeight:'700',color:colors.ink,marginBottom:10},grid:{flexDirection:'row',flexWrap:'wrap',gap:10,marginBottom:20},card:{width:'47%',backgroundColor:colors.surfaceTint,borderWidth:1,borderColor:colors.line,borderRadius:16,padding:14},badge:{width:36,height:36,borderRadius:10,alignItems:'center',justifyContent:'center',marginBottom:10},cardText:{fontWeight:'700',color:colors.ink,fontSize:14,marginBottom:2},cardSub:{fontSize:12,color:colors.muted},chips:{gap:8,paddingBottom:4},tag:{paddingHorizontal:14,paddingVertical:8,borderRadius:999,backgroundColor:colors.surfaceTint,borderWidth:1,borderColor:colors.line},tagText:{fontSize:12,color:colors.muted}});
