const recipes=[
 {id:'potato-egg',title:'감자계란볶음',emoji:'🍳',time:15,difficulty:'쉬움',themes:['간단한 한 끼','저예산 요리'],ingredients:[['감자','2개',true],['계란','2개',true],['양파','1/2개',true],['식용유','1큰술',false],['소금','약간',false]],reason:'감자와 계란을 모두 가지고 있고, 15분 안에 만들 수 있어 추천했어요.',steps:[['🔪','감자를 얇게 썰어주세요.','3분'],['🥚','계란을 풀어 소금 한 꼬집을 섞어주세요.','2분'],['🧅','팬에 기름을 두르고 양파를 볶아주세요.','3분'],['🍳','감자를 넣고 노릇해질 때까지 볶아주세요.','5분'],['✅','계란물을 부어 골고루 섞으면 완성이에요.','2분']]},
 {id:'kimchi-pancake',title:'김치전',emoji:'🥞',time:20,difficulty:'쉬움',themes:['술안주','간단한 한 끼'],ingredients:[['김치','1컵',true],['부침가루','1컵',true],['대파','1/2대',false],['식용유','3큰술',false]],reason:'김치와 대파를 활용해 바삭한 안주를 만들 수 있어요. 부침가루가 필요해요.',steps:[['🥣','김치와 부침가루에 물을 넣어 반죽을 만들어주세요.','5분'],['🔥','팬에 기름을 넉넉히 두르고 반죽을 올려주세요.','3분'],['🥞','앞뒤로 노릇하게 부쳐 완성하세요.','12분']]},
 {id:'stew',title:'김치찌개',emoji:'🍲',time:25,difficulty:'보통',themes:['간단한 한 끼','가족 식사'],ingredients:[['김치','2컵',true],['돼지고기','150g',true],['양파','1/2개',true],['대파','1/2대',false],['다진 마늘','1작은술',false]],reason:'김치와 돼지고기가 있어 든든한 한 끼로 추천했어요.',steps:[['🥩','돼지고기를 냄비에 볶아주세요.','5분'],['🥬','김치와 양파를 넣고 함께 볶아주세요.','5분'],['🍲','물을 붓고 끓인 뒤 대파를 넣어주세요.','15분']]},
 {id:'pasta',title:'마늘 오일 파스타',emoji:'🍝',time:18,difficulty:'쉬움',themes:['간단한 한 끼','15분 요리'],ingredients:[['파스타면','160g',true],['마늘','4쪽',true],['올리브유','4큰술',false],['페페론치노','약간',false]],reason:'간단한 재료로 20분 안에 완성할 수 있는 메뉴예요.',steps:[['🍝','파스타면을 포장지 시간에 맞춰 삶아주세요.','10분'],['🧄','올리브유에 마늘을 약불로 볶아주세요.','5분'],['🍽️','면과 면수를 넣고 잘 섞어주세요.','3분']]}
];
const themes=[['🍳','간단한 한 끼'],['🏕','캠핑'],['🍺','술안주'],['👨‍👩‍👧','가족 식사'],['💸','저예산 요리'],['⏱','15분 요리'],['🥗','건강한 식사']];
const state={ingredients:new Set(),recipe:null,results:[],step:0,checked:new Set(),timer:null,remaining:0};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
function go(id){$$('.view').forEach(v=>v.classList.remove('active-view'));$('#'+id).classList.add('active-view');window.scrollTo({top:0,behavior:'smooth'});}
function toast(message){const t=$('#toast');t.textContent=message;t.classList.add('show');clearTimeout(state.toast);state.toast=setTimeout(()=>t.classList.remove('show'),2400)}
function recipeCard(r,owned=[]){const names=new Set(owned.map(normalize));const have=r.ingredients.filter(x=>names.has(normalize(x[0]))).length;const required=r.ingredients.filter(x=>x[2]).length;return `<button class="recipe-card" data-recipe="${r.id}"><span class="recipe-art">${r.emoji}</span><span class="recipe-info"><h3>${r.title}</h3><p>${r.time}분 · ${r.difficulty} · 재료 ${have}/${r.ingredients.length}</p><span class="badge ${have<required?'warn':''}">${have>=required?'바로 만들 수 있어요':'재료를 조금만 추가해보세요'}</span></span><span>›</span></button>`}
function normalize(v){return ({'파':'대파','계란':'계란','달걀':'계란','마늘':'다진 마늘'}[v.trim()]||v.trim()).toLowerCase()}
function renderThemes(){const html=themes.map(([e,n])=>`<button class="theme-pill" data-theme="${n}">${e} ${n}</button>`).join('');$('#home-themes').innerHTML=html;$('#theme-grid').innerHTML=themes.map(([e,n])=>`<button class="theme-option" data-theme="${n}"><span class="emoji">${e}</span><b>${n}</b></button>`).join('');}
function renderChips(){const list=['감자','양파','계란','대파','김치','돼지고기','마늘','파스타면'];$('#ingredient-chips').innerHTML=list.map(n=>`<button class="chip ${state.ingredients.has(normalize(n))?'selected':''}" data-ing="${n}">${n}</button>`).join('');$('#selected-ingredients').innerHTML=state.ingredients.size?[...state.ingredients].map(n=>`<span class="selected-tag">${n}<button data-remove="${n}">×</button></span>`).join(''):'<span class="muted">아직 선택한 재료가 없어요.</span>';$('#ingredient-count').textContent=state.ingredients.size+'개';}
function findByIngredients(){const owned=[...state.ingredients];const max=Number($('#max-time').value);state.results=recipes.filter(r=>r.time<=max).sort((a,b)=>score(b,owned)-score(a,owned));$('#result-title').textContent='현재 재료로 만들 수 있는 요리';$('#result-subtitle').textContent=owned.join(', ')+'으로 만들 수 있는 레시피를 골라봤어요.';renderResults(owned);go('results');}
function score(r,owned){const o=new Set(owned.map(normalize));return r.ingredients.filter(x=>o.has(normalize(x[0]))).length/r.ingredients.length+(r.time<=15?.2:0)}
function renderResults(owned=[]){const ready=state.results.filter(r=>r.ingredients.filter(x=>owned.map(normalize).includes(normalize(x[0]))).length>=r.ingredients.filter(x=>x[2]).length);const more=state.results.filter(r=>!ready.includes(r));$('#result-content').innerHTML=(ready.length?`<div class="result-group"><h2>지금 바로 만들 수 있어요 <span>${ready.length}</span></h2><div class="recipe-list">${ready.map(r=>recipeCard(r,owned)).join('')}</div></div>`:'')+(more.length?`<div class="result-group"><h2>재료를 조금만 추가하면 돼요 <span>${more.length}</span></h2><div class="recipe-list">${more.map(r=>recipeCard(r,owned)).join('')}</div></div>`:'')||( '<div class="selected-box"><b>조건에 맞는 요리를 찾지 못했어요.</b><p class="muted">재료를 추가하거나 조리 시간을 늘려보세요.</p></div>');bindRecipeCards();}
function showDetail(r){state.recipe=r;$('#detail-content').innerHTML=`<div class="detail-hero">${r.emoji}</div><div class="detail-title"><div><h1>${r.title}</h1><div class="meta">${r.time}분 · ${r.difficulty} · 2인분</div></div><button class="favorite" onclick="toast('찜 목록에 저장했어요')">♡</button></div><div class="reason">💡 ${r.reason}</div><div class="detail-block"><h2>재료</h2>${r.ingredients.map(x=>`<div class="ingredient-row"><span>${x[0]}${x[2]?'':' · 기본 조미료'}</span><b>${x[1]}</b></div>`).join('')}</div><div class="detail-block"><h2>준비 과정</h2><p class="muted">재료를 깨끗이 씻고 필요한 크기로 손질해주세요. 조리 전 모든 재료를 준비하면 더 편해요.</p></div><div class="safety">⚠️ 조리 시간은 재료와 화력에 따라 달라질 수 있어요. 고기·계란은 속까지 충분히 익혀주세요.</div><br /><button class="primary-btn" data-action="open-checklist">재료 확인하기 <span>→</span></button>`;go('detail');}
function showChecklist(){const r=state.recipe;state.checked=new Set(r.ingredients.filter(x=>state.ingredients.has(normalize(x[0]))).map(x=>x[0]));renderChecklist();go('checklist');}
function renderChecklist(){const r=state.recipe;const rows=r.ingredients.map(x=>`<label class="check-row"><input type="checkbox" data-check="${x[0]}" ${state.checked.has(x[0])?'checked':''}><span>${x[0]}</span><small>${x[1]}</small></label>`).join('');const total=r.ingredients.length;$('#checklist-content').innerHTML=`<div class="page-title"><p class="eyebrow">STEP 3 · PREPARE</p><h1>재료를 준비했는지<br />확인해주세요.</h1></div><div class="check-progress"><div class="section-head"><b>준비 현황</b><span id="check-count"></span></div><div class="progress-bar"><span id="check-progress"></span></div></div><div>${rows}</div><div class="add-more"><p><b>더 넣고 싶은 재료가 있나요?</b></p><input id="extra-input" placeholder="예: 버섯, 치즈" /></div><button class="primary-btn" data-action="open-cooking">조리 시작 <span>→</span></button>`;updateProgress();}
function updateProgress(){const total=state.recipe.ingredients.length;const done=state.checked.size;$('#check-count').textContent=`${done}/${total}개 준비 완료`;$('#check-progress').style.width=(done/total*100)+'%';}
function showCooking(){state.step=0;renderCooking();go('cooking');}
function renderCooking(){const r=state.recipe,s=r.steps[state.step];$('#cooking-content').innerHTML=`<div class="page-title"><p class="eyebrow">STEP 4 · COOKING MODE</p><h1>한 단계씩<br />따라 해보세요.</h1></div><div class="step-card"><div class="step-count">${state.step+1} / ${r.steps.length} 단계</div><div class="step-emoji">${s[0]}</div><h1>${s[1]}</h1><p>예상 시간 ${s[2]}</p><div class="timer" id="timer">${state.remaining?formatTime(state.remaining):s[2].replace('분','분 00초')}</div><div class="step-dots">${r.steps.map((_,i)=>`<span class="${i<=state.step?'done':''}"></span>`).join('')}</div></div><div class="step-actions"><button class="secondary-btn" data-action="prev-step">← 이전</button><button class="secondary-btn" data-action="timer">⏱ 타이머</button></div><br /><button class="primary-btn" data-action="next-step">${state.step===r.steps.length-1?'조리 완료':'다음 단계'} <span>→</span></button>`;}
function formatTime(s){return Math.floor(s/60).toString().padStart(2,'0')+':'+(s%60).toString().padStart(2,'0')}
function bindRecipeCards(){$$('.recipe-card').forEach(el=>el.onclick=()=>showDetail(recipes.find(r=>r.id===el.dataset.recipe)));}
document.addEventListener('click',e=>{const action=e.target.closest('[data-action]')?.dataset.action;if(action==='home')go('home');if(action==='ingredients'){renderChips();go('ingredients')}if(action==='themes')go('themes');if(action==='search'){renderSearch();go('search')}if(action==='results')go('results');if(action==='go-detail')go('detail');if(action==='open-checklist')showChecklist();if(action==='go-checklist')go('checklist');if(action==='open-cooking')showCooking();if(action==='prev-step'){if(state.step>0){state.step--;renderCooking()}}if(action==='next-step'){if(state.step<state.recipe.steps.length-1){state.step++;renderCooking()}else{toast('오늘의 요리를 완성했어요!');go('home')}}if(action==='timer')startTimer();const ing=e.target.closest('[data-ing]')?.dataset.ing;if(ing){state.ingredients.has(normalize(ing))?state.ingredients.delete(normalize(ing)):state.ingredients.add(normalize(ing));renderChips()}const remove=e.target.closest('[data-remove]')?.dataset.remove;if(remove){state.ingredients.delete(remove);renderChips()}const theme=e.target.closest('[data-theme]')?.dataset.theme;if(theme){state.results=recipes.filter(r=>r.themes.includes(theme));$('#result-title').textContent=theme+' 추천 요리';$('#result-subtitle').textContent='오늘의 상황에 잘 어울리는 레시피예요.';renderResults([...state.ingredients]);go('results')}});
$('#add-ingredient').onclick=()=>{const i=$('#ingredient-input').value.trim();if(i){state.ingredients.add(normalize(i));$('#ingredient-input').value='';renderChips()}};$('#ingredient-submit').onclick=()=>state.ingredients.size?findByIngredients():toast('재료를 하나 이상 선택해주세요');$('#menu-submit').onclick=renderSearch;function renderSearch(){const q=($('#menu-input')?.value||'').trim();const found=recipes.filter(r=>!q||r.title.includes(q)||r.title.toLowerCase().includes(q.toLowerCase()));$('#search-results').innerHTML=found.length?found.map(r=>recipeCard(r)).join(''):'<div class="selected-box"><b>검색 결과가 없어요.</b><p class="muted">다른 메뉴 이름으로 검색해보세요.</p></div>';bindRecipeCards()}
$$('select').forEach(s=>s.addEventListener('change',()=>{}));$('#checklist').addEventListener('change',e=>{if(e.target.dataset.check){e.target.checked?state.checked.add(e.target.dataset.check):state.checked.delete(e.target.dataset.check);updateProgress()}});function startTimer(){if(state.timer)return;const s=state.recipe.steps[state.step][2];state.remaining=(parseInt(s)||3)*60;state.timer=setInterval(()=>{state.remaining--;const t=$('#timer');if(t)t.textContent=formatTime(state.remaining);if(state.remaining<=0){clearInterval(state.timer);state.timer=null;toast('단계 시간이 끝났어요!')}},1000);}
renderThemes();renderChips();renderSearch();
